name: Bug Report
description: Report an issue or visual bug
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **Your YAML Configuration is Required**
        > Because this card is highly visual and supports so many different dashboard layouts, simply describing a bug in words makes it nearly impossible to troubleshoot. 
        > 
        > To help me fix your issue quickly, **I need to see exactly how you have it configured**. Please paste your card's full YAML code below.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Clearly describe the issue. What did you expect to happen, and what actually happened?
    validations:
      required: true
  - type: textarea
    id: yaml-code
    attributes:
      label: Your Card's YAML Configuration
      description: Paste the exact YAML you are using for the card in your Home Assistant dashboard.
      render: yaml
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context about the problem here, such as screenshots, browser types, or logs.
    validations:
      required: false
